<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parameters/parameter-domain.proto

namespace Proto\Parameters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.parameters.CreateParameterDomainRequest</code>
 */
class CreateParameterDomainRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterDomainProto domain = 1;</code>
     */
    protected $domain = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Parameters\ParameterDomainProto $domain
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ParameterDomain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterDomainProto domain = 1;</code>
     * @return \Proto\Parameters\ParameterDomainProto|null
     */
    public function getDomain()
    {
        return $this->domain;
    }

    public function hasDomain()
    {
        return isset($this->domain);
    }

    public function clearDomain()
    {
        unset($this->domain);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterDomainProto domain = 1;</code>
     * @param \Proto\Parameters\ParameterDomainProto $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkMessage($var, \Proto\Parameters\ParameterDomainProto::class);
        $this->domain = $var;

        return $this;
    }

}

