<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameters/parameter-domain.proto

namespace Proto\Parameters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.parameters.ListParameterDomainsResponse</code>
 */
class ListParameterDomainsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.parameters.ParameterDomainProto domains = 1;</code>
     */
    private $domains;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\Parameters\ParameterDomainProto>|\Google\Protobuf\Internal\RepeatedField $domains
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ParameterDomain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.parameters.ParameterDomainProto domains = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomains()
    {
        return $this->domains;
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.parameters.ParameterDomainProto domains = 1;</code>
     * @param array<\Proto\Parameters\ParameterDomainProto>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomains($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Parameters\ParameterDomainProto::class);
        $this->domains = $arr;

        return $this;
    }

}

