<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameters/parameter-domain.proto

namespace Proto\Parameters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.parameters.ListParameterDomainsRequest</code>
 */
class ListParameterDomainsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 page = 1;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>int32 page_size = 2;</code>
     */
    protected $page_size = 0;
    /**
     * optional: case-insensitive match on code/name/description
     *
     * Generated from protobuf field <code>optional string search = 3;</code>
     */
    protected $search = null;
    /**
     * optional: filter by managed_by_module
     *
     * Generated from protobuf field <code>optional int64 module_id = 4;</code>
     */
    protected $module_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $page
     *     @type int $page_size
     *     @type string $search
     *           optional: case-insensitive match on code/name/description
     *     @type int|string $module_id
     *           optional: filter by managed_by_module
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ParameterDomain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 page = 1;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 2;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * optional: case-insensitive match on code/name/description
     *
     * Generated from protobuf field <code>optional string search = 3;</code>
     * @return string
     */
    public function getSearch()
    {
        return isset($this->search) ? $this->search : '';
    }

    public function hasSearch()
    {
        return isset($this->search);
    }

    public function clearSearch()
    {
        unset($this->search);
    }

    /**
     * optional: case-insensitive match on code/name/description
     *
     * Generated from protobuf field <code>optional string search = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSearch($var)
    {
        GPBUtil::checkString($var, True);
        $this->search = $var;

        return $this;
    }

    /**
     * optional: filter by managed_by_module
     *
     * Generated from protobuf field <code>optional int64 module_id = 4;</code>
     * @return int|string
     */
    public function getModuleId()
    {
        return isset($this->module_id) ? $this->module_id : 0;
    }

    public function hasModuleId()
    {
        return isset($this->module_id);
    }

    public function clearModuleId()
    {
        unset($this->module_id);
    }

    /**
     * optional: filter by managed_by_module
     *
     * Generated from protobuf field <code>optional int64 module_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setModuleId($var)
    {
        GPBUtil::checkInt64($var);
        $this->module_id = $var;

        return $this;
    }

}

