<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parameters/parameter-definition.proto

namespace Proto\Parameters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.parameters.ListParameterDefinitionsResponse</code>
 */
class ListParameterDefinitionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.parameters.ParameterDefinitionProto definitions = 1;</code>
     */
    private $definitions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Parameters\ParameterDefinitionProto[] $definitions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ParameterDefinition::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.parameters.ParameterDefinitionProto definitions = 1;</code>
     * @return RepeatedField<\Proto\Parameters\ParameterDefinitionProto>
     */
    public function getDefinitions()
    {
        return $this->definitions;
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.parameters.ParameterDefinitionProto definitions = 1;</code>
     * @param \Proto\Parameters\ParameterDefinitionProto[] $var
     * @return $this
     */
    public function setDefinitions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Parameters\ParameterDefinitionProto::class);
        $this->definitions = $arr;

        return $this;
    }

}

