<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameters/parameter-domain.proto

namespace Proto\Parameters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ------------ MESSAGES ------------
 *
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.parameters.ParameterDomainProto</code>
 */
class ParameterDomainProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string domain_code = 2;</code>
     */
    protected $domain_code = '';
    /**
     * Generated from protobuf field <code>string domain_name = 3;</code>
     */
    protected $domain_name = '';
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>int64 managed_by_module = 5;</code>
     */
    protected $managed_by_module = 0;
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.modules.SystemModule system_module = 6;</code>
     */
    protected $system_module = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $domain_code
     *     @type string $domain_name
     *     @type string $description
     *     @type int|string $managed_by_module
     *     @type \Proto\Modules\SystemModule $system_module
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ParameterDomain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string domain_code = 2;</code>
     * @return string
     */
    public function getDomainCode()
    {
        return $this->domain_code;
    }

    /**
     * Generated from protobuf field <code>string domain_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string domain_name = 3;</code>
     * @return string
     */
    public function getDomainName()
    {
        return $this->domain_name;
    }

    /**
     * Generated from protobuf field <code>string domain_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainName($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 managed_by_module = 5;</code>
     * @return int|string
     */
    public function getManagedByModule()
    {
        return $this->managed_by_module;
    }

    /**
     * Generated from protobuf field <code>int64 managed_by_module = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setManagedByModule($var)
    {
        GPBUtil::checkInt64($var);
        $this->managed_by_module = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.modules.SystemModule system_module = 6;</code>
     * @return \Proto\Modules\SystemModule|null
     */
    public function getSystemModule()
    {
        return $this->system_module;
    }

    public function hasSystemModule()
    {
        return isset($this->system_module);
    }

    public function clearSystemModule()
    {
        unset($this->system_module);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.modules.SystemModule system_module = 6;</code>
     * @param \Proto\Modules\SystemModule $var
     * @return $this
     */
    public function setSystemModule($var)
    {
        GPBUtil::checkMessage($var, \Proto\Modules\SystemModule::class);
        $this->system_module = $var;

        return $this;
    }

}

