<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parameters/parameter-definition.proto

namespace Proto\Parameters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ------------ MESSAGE ------------
 *
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.parameters.ParameterDefinitionProto</code>
 */
class ParameterDefinitionProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 domain_id = 2;</code>
     */
    protected $domain_id = 0;
    /**
     * Generated from protobuf field <code>bool is_effective_date_driven = 3;</code>
     */
    protected $is_effective_date_driven = false;
    /**
     * Generated from protobuf field <code>string parameter_name = 4;</code>
     */
    protected $parameter_name = '';
    /**
     * Generated from protobuf field <code>string attribute1_name = 5;</code>
     */
    protected $attribute1_name = '';
    /**
     * Generated from protobuf field <code>string attribute2_name = 6;</code>
     */
    protected $attribute2_name = '';
    /**
     * Generated from protobuf field <code>string attribute3_name = 7;</code>
     */
    protected $attribute3_name = '';
    /**
     * Generated from protobuf field <code>string attribute4_name = 8;</code>
     */
    protected $attribute4_name = '';
    /**
     * Generated from protobuf field <code>string attribute5_name = 9;</code>
     */
    protected $attribute5_name = '';
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterDomainProto domain = 10;</code>
     */
    protected $domain = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $domain_id
     *     @type bool $is_effective_date_driven
     *     @type string $parameter_name
     *     @type string $attribute1_name
     *     @type string $attribute2_name
     *     @type string $attribute3_name
     *     @type string $attribute4_name
     *     @type string $attribute5_name
     *     @type \Proto\Parameters\ParameterDomainProto $domain
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ParameterDefinition::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 domain_id = 2;</code>
     * @return int|string
     */
    public function getDomainId()
    {
        return $this->domain_id;
    }

    /**
     * Generated from protobuf field <code>int64 domain_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDomainId($var)
    {
        GPBUtil::checkInt64($var);
        $this->domain_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_effective_date_driven = 3;</code>
     * @return bool
     */
    public function getIsEffectiveDateDriven()
    {
        return $this->is_effective_date_driven;
    }

    /**
     * Generated from protobuf field <code>bool is_effective_date_driven = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEffectiveDateDriven($var)
    {
        GPBUtil::checkBool($var);
        $this->is_effective_date_driven = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parameter_name = 4;</code>
     * @return string
     */
    public function getParameterName()
    {
        return $this->parameter_name;
    }

    /**
     * Generated from protobuf field <code>string parameter_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParameterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->parameter_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attribute1_name = 5;</code>
     * @return string
     */
    public function getAttribute1Name()
    {
        return $this->attribute1_name;
    }

    /**
     * Generated from protobuf field <code>string attribute1_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAttribute1Name($var)
    {
        GPBUtil::checkString($var, True);
        $this->attribute1_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attribute2_name = 6;</code>
     * @return string
     */
    public function getAttribute2Name()
    {
        return $this->attribute2_name;
    }

    /**
     * Generated from protobuf field <code>string attribute2_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAttribute2Name($var)
    {
        GPBUtil::checkString($var, True);
        $this->attribute2_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attribute3_name = 7;</code>
     * @return string
     */
    public function getAttribute3Name()
    {
        return $this->attribute3_name;
    }

    /**
     * Generated from protobuf field <code>string attribute3_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAttribute3Name($var)
    {
        GPBUtil::checkString($var, True);
        $this->attribute3_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attribute4_name = 8;</code>
     * @return string
     */
    public function getAttribute4Name()
    {
        return $this->attribute4_name;
    }

    /**
     * Generated from protobuf field <code>string attribute4_name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAttribute4Name($var)
    {
        GPBUtil::checkString($var, True);
        $this->attribute4_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attribute5_name = 9;</code>
     * @return string
     */
    public function getAttribute5Name()
    {
        return $this->attribute5_name;
    }

    /**
     * Generated from protobuf field <code>string attribute5_name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setAttribute5Name($var)
    {
        GPBUtil::checkString($var, True);
        $this->attribute5_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterDomainProto domain = 10;</code>
     * @return \Proto\Parameters\ParameterDomainProto|null
     */
    public function getDomain()
    {
        return $this->domain;
    }

    public function hasDomain()
    {
        return isset($this->domain);
    }

    public function clearDomain()
    {
        unset($this->domain);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterDomainProto domain = 10;</code>
     * @param \Proto\Parameters\ParameterDomainProto $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkMessage($var, \Proto\Parameters\ParameterDomainProto::class);
        $this->domain = $var;

        return $this;
    }

}

