<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parameters/parameter-definition.proto

namespace Proto\Parameters;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.parameters.UpdateParameterDefinitionRequest</code>
 */
class UpdateParameterDefinitionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterDefinitionProto definition = 1;</code>
     */
    protected $definition = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Parameters\ParameterDefinitionProto $definition
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ParameterDefinition::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterDefinitionProto definition = 1;</code>
     * @return \Proto\Parameters\ParameterDefinitionProto|null
     */
    public function getDefinition()
    {
        return $this->definition;
    }

    public function hasDefinition()
    {
        return isset($this->definition);
    }

    public function clearDefinition()
    {
        unset($this->definition);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterDefinitionProto definition = 1;</code>
     * @param \Proto\Parameters\ParameterDefinitionProto $var
     * @return $this
     */
    public function setDefinition($var)
    {
        GPBUtil::checkMessage($var, \Proto\Parameters\ParameterDefinitionProto::class);
        $this->definition = $var;

        return $this;
    }

}

