<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/party.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.consumers.CreatePartyRequest</code>
 */
class CreatePartyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 party_code = 1;</code>
     */
    protected $party_code = 0;
    /**
     * Generated from protobuf field <code>string party_legacy_code = 2;</code>
     */
    protected $party_legacy_code = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int64 party_type_id = 4;</code>
     */
    protected $party_type_id = 0;
    /**
     * Generated from protobuf field <code>int64 status_id = 5;</code>
     */
    protected $status_id = 0;
    /**
     * Generated from protobuf field <code>int64 mobile_number = 6;</code>
     */
    protected $mobile_number = 0;
    /**
     * Generated from protobuf field <code>int64 telephone_number = 7;</code>
     */
    protected $telephone_number = 0;
    /**
     * Generated from protobuf field <code>string email_address = 8;</code>
     */
    protected $email_address = '';
    /**
     * Generated from protobuf field <code>string address = 9;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>int64 fax_number = 10;</code>
     */
    protected $fax_number = 0;
    /**
     * Generated from protobuf field <code>optional int32 created_by = 11;</code>
     */
    protected $created_by = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $party_code
     *     @type string $party_legacy_code
     *     @type string $name
     *     @type int|string $party_type_id
     *     @type int|string $status_id
     *     @type int|string $mobile_number
     *     @type int|string $telephone_number
     *     @type string $email_address
     *     @type string $address
     *     @type int|string $fax_number
     *     @type int $created_by
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Party::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 party_code = 1;</code>
     * @return int
     */
    public function getPartyCode()
    {
        return $this->party_code;
    }

    /**
     * Generated from protobuf field <code>int32 party_code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPartyCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->party_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string party_legacy_code = 2;</code>
     * @return string
     */
    public function getPartyLegacyCode()
    {
        return $this->party_legacy_code;
    }

    /**
     * Generated from protobuf field <code>string party_legacy_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPartyLegacyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->party_legacy_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 party_type_id = 4;</code>
     * @return int|string
     */
    public function getPartyTypeId()
    {
        return $this->party_type_id;
    }

    /**
     * Generated from protobuf field <code>int64 party_type_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartyTypeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->party_type_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status_id = 5;</code>
     * @return int|string
     */
    public function getStatusId()
    {
        return $this->status_id;
    }

    /**
     * Generated from protobuf field <code>int64 status_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatusId($var)
    {
        GPBUtil::checkInt64($var);
        $this->status_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 mobile_number = 6;</code>
     * @return int|string
     */
    public function getMobileNumber()
    {
        return $this->mobile_number;
    }

    /**
     * Generated from protobuf field <code>int64 mobile_number = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMobileNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->mobile_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 telephone_number = 7;</code>
     * @return int|string
     */
    public function getTelephoneNumber()
    {
        return $this->telephone_number;
    }

    /**
     * Generated from protobuf field <code>int64 telephone_number = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTelephoneNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->telephone_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email_address = 8;</code>
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->email_address;
    }

    /**
     * Generated from protobuf field <code>string email_address = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEmailAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->email_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 9;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fax_number = 10;</code>
     * @return int|string
     */
    public function getFaxNumber()
    {
        return $this->fax_number;
    }

    /**
     * Generated from protobuf field <code>int64 fax_number = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFaxNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->fax_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 created_by = 11;</code>
     * @return int
     */
    public function getCreatedBy()
    {
        return isset($this->created_by) ? $this->created_by : 0;
    }

    public function hasCreatedBy()
    {
        return isset($this->created_by);
    }

    public function clearCreatedBy()
    {
        unset($this->created_by);
    }

    /**
     * Generated from protobuf field <code>optional int32 created_by = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_by = $var;

        return $this;
    }

}

