<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/party.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.consumers.DeletePartyRequest</code>
 */
class DeletePartyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 party_id = 1;</code>
     */
    protected $party_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $party_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Party::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 party_id = 1;</code>
     * @return int
     */
    public function getPartyId()
    {
        return $this->party_id;
    }

    /**
     * Generated from protobuf field <code>int32 party_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPartyId($var)
    {
        GPBUtil::checkInt32($var);
        $this->party_id = $var;

        return $this;
    }

}

