<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/party.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.consumers.GetPartyByVersionIdRequest</code>
 */
class GetPartyByVersionIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 version_id = 1;</code>
     */
    protected $version_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $version_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Party::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 version_id = 1;</code>
     * @return int|string
     */
    public function getVersionId()
    {
        return $this->version_id;
    }

    /**
     * Generated from protobuf field <code>int64 version_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->version_id = $var;

        return $this;
    }

}

