<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/office.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OfficeIdRequest</code>
 */
class OfficeIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 office_id = 1;</code>
     */
    protected $office_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $office_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Office::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 office_id = 1;</code>
     * @return int
     */
    public function getOfficeId()
    {
        return $this->office_id;
    }

    /**
     * Generated from protobuf field <code>int32 office_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOfficeId($var)
    {
        GPBUtil::checkInt32($var);
        $this->office_id = $var;

        return $this;
    }

}

