<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/office.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OfficeMessage</code>
 */
class OfficeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 office_id = 1;</code>
     */
    protected $office_id = 0;
    /**
     * Generated from protobuf field <code>optional int32 office_code = 2;</code>
     */
    protected $office_code = null;
    /**
     * Generated from protobuf field <code>string office_description = 3;</code>
     */
    protected $office_description = '';
    /**
     * Generated from protobuf field <code>optional int32 parent_office_id = 5;</code>
     */
    protected $parent_office_id = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct contact_folio = 8;</code>
     */
    protected $contact_folio = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp effective_start = 9;</code>
     */
    protected $effective_start = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp effective_end = 10;</code>
     */
    protected $effective_end = null;
    /**
     * Generated from protobuf field <code>bool is_current = 11;</code>
     */
    protected $is_current = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 12;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 13;</code>
     */
    protected $updated_at = null;
    /**
     * Generated from protobuf field <code>int32 created_by = 14;</code>
     */
    protected $created_by = 0;
    /**
     * Generated from protobuf field <code>int32 updated_by = 15;</code>
     */
    protected $updated_by = 0;
    /**
     * Generated from protobuf field <code>optional int64 office_type_id = 16;</code>
     */
    protected $office_type_id = null;
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterValueProto office_type = 17;</code>
     */
    protected $office_type = null;
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OfficeMessage parent_office = 18;</code>
     */
    protected $parent_office = null;
    /**
     * Generated from protobuf field <code>optional int32 location_id = 19;</code>
     */
    protected $location_id = null;
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage location = 20;</code>
     */
    protected $location = null;
    /**
     * Generated from protobuf field <code>optional int32 office_address_id = 21;</code>
     */
    protected $office_address_id = null;
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementAddressMessage office_address = 22;</code>
     */
    protected $office_address = null;
    /**
     * Generated from protobuf field <code>string office_name = 23;</code>
     */
    protected $office_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $office_id
     *     @type int $office_code
     *     @type string $office_description
     *     @type int $parent_office_id
     *     @type \Google\Protobuf\Struct $contact_folio
     *     @type \Google\Protobuf\Timestamp $effective_start
     *     @type \Google\Protobuf\Timestamp $effective_end
     *     @type bool $is_current
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     *     @type int $created_by
     *     @type int $updated_by
     *     @type int|string $office_type_id
     *     @type \Proto\Parameters\ParameterValueProto $office_type
     *     @type \Proto\Consumers\OfficeMessage $parent_office
     *     @type int $location_id
     *     @type \Proto\Consumers\OrgElementLocationMessage $location
     *     @type int $office_address_id
     *     @type \Proto\Consumers\OrgElementAddressMessage $office_address
     *     @type string $office_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Office::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 office_id = 1;</code>
     * @return int
     */
    public function getOfficeId()
    {
        return $this->office_id;
    }

    /**
     * Generated from protobuf field <code>int32 office_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOfficeId($var)
    {
        GPBUtil::checkInt32($var);
        $this->office_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 office_code = 2;</code>
     * @return int
     */
    public function getOfficeCode()
    {
        return isset($this->office_code) ? $this->office_code : 0;
    }

    public function hasOfficeCode()
    {
        return isset($this->office_code);
    }

    public function clearOfficeCode()
    {
        unset($this->office_code);
    }

    /**
     * Generated from protobuf field <code>optional int32 office_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOfficeCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->office_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string office_description = 3;</code>
     * @return string
     */
    public function getOfficeDescription()
    {
        return $this->office_description;
    }

    /**
     * Generated from protobuf field <code>string office_description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOfficeDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->office_description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 parent_office_id = 5;</code>
     * @return int
     */
    public function getParentOfficeId()
    {
        return isset($this->parent_office_id) ? $this->parent_office_id : 0;
    }

    public function hasParentOfficeId()
    {
        return isset($this->parent_office_id);
    }

    public function clearParentOfficeId()
    {
        unset($this->parent_office_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 parent_office_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setParentOfficeId($var)
    {
        GPBUtil::checkInt32($var);
        $this->parent_office_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct contact_folio = 8;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getContactFolio()
    {
        return $this->contact_folio;
    }

    public function hasContactFolio()
    {
        return isset($this->contact_folio);
    }

    public function clearContactFolio()
    {
        unset($this->contact_folio);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct contact_folio = 8;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setContactFolio($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->contact_folio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp effective_start = 9;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEffectiveStart()
    {
        return $this->effective_start;
    }

    public function hasEffectiveStart()
    {
        return isset($this->effective_start);
    }

    public function clearEffectiveStart()
    {
        unset($this->effective_start);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp effective_start = 9;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEffectiveStart($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->effective_start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp effective_end = 10;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEffectiveEnd()
    {
        return $this->effective_end;
    }

    public function hasEffectiveEnd()
    {
        return isset($this->effective_end);
    }

    public function clearEffectiveEnd()
    {
        unset($this->effective_end);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp effective_end = 10;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEffectiveEnd($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->effective_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_current = 11;</code>
     * @return bool
     */
    public function getIsCurrent()
    {
        return $this->is_current;
    }

    /**
     * Generated from protobuf field <code>bool is_current = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCurrent($var)
    {
        GPBUtil::checkBool($var);
        $this->is_current = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 12;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 12;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 13;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 13;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 created_by = 14;</code>
     * @return int
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Generated from protobuf field <code>int32 created_by = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 updated_by = 15;</code>
     * @return int
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Generated from protobuf field <code>int32 updated_by = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdatedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 office_type_id = 16;</code>
     * @return int|string
     */
    public function getOfficeTypeId()
    {
        return isset($this->office_type_id) ? $this->office_type_id : 0;
    }

    public function hasOfficeTypeId()
    {
        return isset($this->office_type_id);
    }

    public function clearOfficeTypeId()
    {
        unset($this->office_type_id);
    }

    /**
     * Generated from protobuf field <code>optional int64 office_type_id = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOfficeTypeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->office_type_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterValueProto office_type = 17;</code>
     * @return \Proto\Parameters\ParameterValueProto|null
     */
    public function getOfficeType()
    {
        return $this->office_type;
    }

    public function hasOfficeType()
    {
        return isset($this->office_type);
    }

    public function clearOfficeType()
    {
        unset($this->office_type);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterValueProto office_type = 17;</code>
     * @param \Proto\Parameters\ParameterValueProto $var
     * @return $this
     */
    public function setOfficeType($var)
    {
        GPBUtil::checkMessage($var, \Proto\Parameters\ParameterValueProto::class);
        $this->office_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OfficeMessage parent_office = 18;</code>
     * @return \Proto\Consumers\OfficeMessage|null
     */
    public function getParentOffice()
    {
        return $this->parent_office;
    }

    public function hasParentOffice()
    {
        return isset($this->parent_office);
    }

    public function clearParentOffice()
    {
        unset($this->parent_office);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OfficeMessage parent_office = 18;</code>
     * @param \Proto\Consumers\OfficeMessage $var
     * @return $this
     */
    public function setParentOffice($var)
    {
        GPBUtil::checkMessage($var, \Proto\Consumers\OfficeMessage::class);
        $this->parent_office = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 location_id = 19;</code>
     * @return int
     */
    public function getLocationId()
    {
        return isset($this->location_id) ? $this->location_id : 0;
    }

    public function hasLocationId()
    {
        return isset($this->location_id);
    }

    public function clearLocationId()
    {
        unset($this->location_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 location_id = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationId($var)
    {
        GPBUtil::checkInt32($var);
        $this->location_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage location = 20;</code>
     * @return \Proto\Consumers\OrgElementLocationMessage|null
     */
    public function getLocation()
    {
        return $this->location;
    }

    public function hasLocation()
    {
        return isset($this->location);
    }

    public function clearLocation()
    {
        unset($this->location);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage location = 20;</code>
     * @param \Proto\Consumers\OrgElementLocationMessage $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \Proto\Consumers\OrgElementLocationMessage::class);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 office_address_id = 21;</code>
     * @return int
     */
    public function getOfficeAddressId()
    {
        return isset($this->office_address_id) ? $this->office_address_id : 0;
    }

    public function hasOfficeAddressId()
    {
        return isset($this->office_address_id);
    }

    public function clearOfficeAddressId()
    {
        unset($this->office_address_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 office_address_id = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setOfficeAddressId($var)
    {
        GPBUtil::checkInt32($var);
        $this->office_address_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementAddressMessage office_address = 22;</code>
     * @return \Proto\Consumers\OrgElementAddressMessage|null
     */
    public function getOfficeAddress()
    {
        return $this->office_address;
    }

    public function hasOfficeAddress()
    {
        return isset($this->office_address);
    }

    public function clearOfficeAddress()
    {
        unset($this->office_address);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementAddressMessage office_address = 22;</code>
     * @param \Proto\Consumers\OrgElementAddressMessage $var
     * @return $this
     */
    public function setOfficeAddress($var)
    {
        GPBUtil::checkMessage($var, \Proto\Consumers\OrgElementAddressMessage::class);
        $this->office_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string office_name = 23;</code>
     * @return string
     */
    public function getOfficeName()
    {
        return $this->office_name;
    }

    /**
     * Generated from protobuf field <code>string office_name = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setOfficeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->office_name = $var;

        return $this;
    }

}

