<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/office.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OfficeListRequest</code>
 */
class OfficeListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string office_type = 1;</code>
     */
    protected $office_type = null;
    /**
     * searches office_code
     *
     * Generated from protobuf field <code>optional string search = 2;</code>
     */
    protected $search = null;
    /**
     * Generated from protobuf field <code>optional string office_name = 3;</code>
     */
    protected $office_name = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $office_type
     *     @type string $search
     *           searches office_code
     *     @type string $office_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Office::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string office_type = 1;</code>
     * @return string
     */
    public function getOfficeType()
    {
        return isset($this->office_type) ? $this->office_type : '';
    }

    public function hasOfficeType()
    {
        return isset($this->office_type);
    }

    public function clearOfficeType()
    {
        unset($this->office_type);
    }

    /**
     * Generated from protobuf field <code>optional string office_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOfficeType($var)
    {
        GPBUtil::checkString($var, True);
        $this->office_type = $var;

        return $this;
    }

    /**
     * searches office_code
     *
     * Generated from protobuf field <code>optional string search = 2;</code>
     * @return string
     */
    public function getSearch()
    {
        return isset($this->search) ? $this->search : '';
    }

    public function hasSearch()
    {
        return isset($this->search);
    }

    public function clearSearch()
    {
        unset($this->search);
    }

    /**
     * searches office_code
     *
     * Generated from protobuf field <code>optional string search = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSearch($var)
    {
        GPBUtil::checkString($var, True);
        $this->search = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string office_name = 3;</code>
     * @return string
     */
    public function getOfficeName()
    {
        return isset($this->office_name) ? $this->office_name : '';
    }

    public function hasOfficeName()
    {
        return isset($this->office_name);
    }

    public function clearOfficeName()
    {
        unset($this->office_name);
    }

    /**
     * Generated from protobuf field <code>optional string office_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOfficeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->office_name = $var;

        return $this;
    }

}

