<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/office.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OfficeResponse</code>
 */
class OfficeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OfficeMessage office = 1;</code>
     */
    protected $office = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Consumers\OfficeMessage $office
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Office::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OfficeMessage office = 1;</code>
     * @return \Proto\Consumers\OfficeMessage|null
     */
    public function getOffice()
    {
        return $this->office;
    }

    public function hasOffice()
    {
        return isset($this->office);
    }

    public function clearOffice()
    {
        unset($this->office);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OfficeMessage office = 1;</code>
     * @param \Proto\Consumers\OfficeMessage $var
     * @return $this
     */
    public function setOffice($var)
    {
        GPBUtil::checkMessage($var, \Proto\Consumers\OfficeMessage::class);
        $this->office = $var;

        return $this;
    }

}

