<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/office.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OfficeListResponse</code>
 */
class OfficeListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.grpc.consumers.OfficeMessage offices = 1;</code>
     */
    private $offices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\Consumers\OfficeMessage>|\Google\Protobuf\Internal\RepeatedField $offices
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Office::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.grpc.consumers.OfficeMessage offices = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOffices()
    {
        return $this->offices;
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.grpc.consumers.OfficeMessage offices = 1;</code>
     * @param array<\Proto\Consumers\OfficeMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOffices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Consumers\OfficeMessage::class);
        $this->offices = $arr;

        return $this;
    }

}

