<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/org_element_address.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OrgElementAddressResponse</code>
 */
class OrgElementAddressResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementAddressMessage address = 1;</code>
     */
    protected $address = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Consumers\OrgElementAddressMessage $address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrgElementAddress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementAddressMessage address = 1;</code>
     * @return \Proto\Consumers\OrgElementAddressMessage|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementAddressMessage address = 1;</code>
     * @param \Proto\Consumers\OrgElementAddressMessage $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Proto\Consumers\OrgElementAddressMessage::class);
        $this->address = $var;

        return $this;
    }

}

