<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/org_element_location.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OrgElementLocationIdRequest</code>
 */
class OrgElementLocationIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 location_id = 1;</code>
     */
    protected $location_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $location_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrgElementLocation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 location_id = 1;</code>
     * @return int
     */
    public function getLocationId()
    {
        return $this->location_id;
    }

    /**
     * Generated from protobuf field <code>int32 location_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationId($var)
    {
        GPBUtil::checkInt32($var);
        $this->location_id = $var;

        return $this;
    }

}

