<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/org_element_address.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OrgElementAddressIdRequest</code>
 */
class OrgElementAddressIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 org_element_address_id = 1;</code>
     */
    protected $org_element_address_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $org_element_address_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrgElementAddress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 org_element_address_id = 1;</code>
     * @return int
     */
    public function getOrgElementAddressId()
    {
        return $this->org_element_address_id;
    }

    /**
     * Generated from protobuf field <code>int32 org_element_address_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOrgElementAddressId($var)
    {
        GPBUtil::checkInt32($var);
        $this->org_element_address_id = $var;

        return $this;
    }

}

