<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/org_element_location.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage</code>
 */
class OrgElementLocationMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 location_id = 1;</code>
     */
    protected $location_id = 0;
    /**
     * Generated from protobuf field <code>int32 location_type_id = 2;</code>
     */
    protected $location_type_id = 0;
    /**
     * Generated from protobuf field <code>double latitude = 3;</code>
     */
    protected $latitude = 0.0;
    /**
     * Generated from protobuf field <code>double longitude = 4;</code>
     */
    protected $longitude = 0.0;
    /**
     * Generated from protobuf field <code>string place_name = 5;</code>
     */
    protected $place_name = '';
    /**
     * Generated from protobuf field <code>int32 district_region_id = 6;</code>
     */
    protected $district_region_id = 0;
    /**
     * Generated from protobuf field <code>int32 taluk_region_id = 7;</code>
     */
    protected $taluk_region_id = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct region_info = 8;</code>
     */
    protected $region_info = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 10;</code>
     */
    protected $updated_at = null;
    /**
     * Generated from protobuf field <code>int32 created_by = 11;</code>
     */
    protected $created_by = 0;
    /**
     * Generated from protobuf field <code>int32 updated_by = 12;</code>
     */
    protected $updated_by = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $location_id
     *     @type int $location_type_id
     *     @type float $latitude
     *     @type float $longitude
     *     @type string $place_name
     *     @type int $district_region_id
     *     @type int $taluk_region_id
     *     @type \Google\Protobuf\Struct $region_info
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     *     @type int $created_by
     *     @type int $updated_by
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrgElementLocation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 location_id = 1;</code>
     * @return int
     */
    public function getLocationId()
    {
        return $this->location_id;
    }

    /**
     * Generated from protobuf field <code>int32 location_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationId($var)
    {
        GPBUtil::checkInt32($var);
        $this->location_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location_type_id = 2;</code>
     * @return int
     */
    public function getLocationTypeId()
    {
        return $this->location_type_id;
    }

    /**
     * Generated from protobuf field <code>int32 location_type_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationTypeId($var)
    {
        GPBUtil::checkInt32($var);
        $this->location_type_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double latitude = 3;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>double latitude = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double longitude = 4;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>double longitude = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->longitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string place_name = 5;</code>
     * @return string
     */
    public function getPlaceName()
    {
        return $this->place_name;
    }

    /**
     * Generated from protobuf field <code>string place_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->place_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 district_region_id = 6;</code>
     * @return int
     */
    public function getDistrictRegionId()
    {
        return $this->district_region_id;
    }

    /**
     * Generated from protobuf field <code>int32 district_region_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setDistrictRegionId($var)
    {
        GPBUtil::checkInt32($var);
        $this->district_region_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 taluk_region_id = 7;</code>
     * @return int
     */
    public function getTalukRegionId()
    {
        return $this->taluk_region_id;
    }

    /**
     * Generated from protobuf field <code>int32 taluk_region_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTalukRegionId($var)
    {
        GPBUtil::checkInt32($var);
        $this->taluk_region_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct region_info = 8;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getRegionInfo()
    {
        return $this->region_info;
    }

    public function hasRegionInfo()
    {
        return isset($this->region_info);
    }

    public function clearRegionInfo()
    {
        unset($this->region_info);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct region_info = 8;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setRegionInfo($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->region_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 10;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 10;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 created_by = 11;</code>
     * @return int
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Generated from protobuf field <code>int32 created_by = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 updated_by = 12;</code>
     * @return int
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Generated from protobuf field <code>int32 updated_by = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdatedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_by = $var;

        return $this;
    }

}

