<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/org_element_location.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OrgElementLocationListResponse</code>
 */
class OrgElementLocationListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage locations = 1;</code>
     */
    private $locations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\Consumers\OrgElementLocationMessage>|\Google\Protobuf\Internal\RepeatedField $locations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrgElementLocation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage locations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocations()
    {
        return $this->locations;
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage locations = 1;</code>
     * @param array<\Proto\Consumers\OrgElementLocationMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Consumers\OrgElementLocationMessage::class);
        $this->locations = $arr;

        return $this;
    }

}

