<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/org_element_address.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OrgElementAddressListResponse</code>
 */
class OrgElementAddressListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.grpc.consumers.OrgElementAddressMessage addresses = 1;</code>
     */
    private $addresses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\Consumers\OrgElementAddressMessage>|\Google\Protobuf\Internal\RepeatedField $addresses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrgElementAddress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.grpc.consumers.OrgElementAddressMessage addresses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.grpc.consumers.OrgElementAddressMessage addresses = 1;</code>
     * @param array<\Proto\Consumers\OrgElementAddressMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Consumers\OrgElementAddressMessage::class);
        $this->addresses = $arr;

        return $this;
    }

}

