<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/org_element_location.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OrgElementLocationResponse</code>
 */
class OrgElementLocationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage org_element_location = 1;</code>
     */
    protected $org_element_location = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Consumers\OrgElementLocationMessage $org_element_location
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrgElementLocation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage org_element_location = 1;</code>
     * @return \Proto\Consumers\OrgElementLocationMessage|null
     */
    public function getOrgElementLocation()
    {
        return $this->org_element_location;
    }

    public function hasOrgElementLocation()
    {
        return isset($this->org_element_location);
    }

    public function clearOrgElementLocation()
    {
        unset($this->org_element_location);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.grpc.consumers.OrgElementLocationMessage org_element_location = 1;</code>
     * @param \Proto\Consumers\OrgElementLocationMessage $var
     * @return $this
     */
    public function setOrgElementLocation($var)
    {
        GPBUtil::checkMessage($var, \Proto\Consumers\OrgElementLocationMessage::class);
        $this->org_element_location = $var;

        return $this;
    }

}

