<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/org_element_address.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.grpc.consumers.OrgElementAddressCreateRequest</code>
 */
class OrgElementAddressCreateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address_line1 = 1;</code>
     */
    protected $address_line1 = '';
    /**
     * Generated from protobuf field <code>string address_line2 = 2;</code>
     */
    protected $address_line2 = '';
    /**
     * Generated from protobuf field <code>string city_town_village = 3;</code>
     */
    protected $city_town_village = '';
    /**
     * Generated from protobuf field <code>string pincode = 4;</code>
     */
    protected $pincode = '';
    /**
     * Generated from protobuf field <code>int32 district_id = 5;</code>
     */
    protected $district_id = 0;
    /**
     * Generated from protobuf field <code>int32 state_id = 6;</code>
     */
    protected $state_id = 0;
    /**
     * Generated from protobuf field <code>double latitude = 7;</code>
     */
    protected $latitude = 0.0;
    /**
     * Generated from protobuf field <code>double longitude = 8;</code>
     */
    protected $longitude = 0.0;
    /**
     * Generated from protobuf field <code>int32 created_by = 9;</code>
     */
    protected $created_by = 0;
    /**
     * Generated from protobuf field <code>int32 updated_by = 10;</code>
     */
    protected $updated_by = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address_line1
     *     @type string $address_line2
     *     @type string $city_town_village
     *     @type string $pincode
     *     @type int $district_id
     *     @type int $state_id
     *     @type float $latitude
     *     @type float $longitude
     *     @type int $created_by
     *     @type int $updated_by
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrgElementAddress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address_line1 = 1;</code>
     * @return string
     */
    public function getAddressLine1()
    {
        return $this->address_line1;
    }

    /**
     * Generated from protobuf field <code>string address_line1 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressLine1($var)
    {
        GPBUtil::checkString($var, True);
        $this->address_line1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address_line2 = 2;</code>
     * @return string
     */
    public function getAddressLine2()
    {
        return $this->address_line2;
    }

    /**
     * Generated from protobuf field <code>string address_line2 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressLine2($var)
    {
        GPBUtil::checkString($var, True);
        $this->address_line2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city_town_village = 3;</code>
     * @return string
     */
    public function getCityTownVillage()
    {
        return $this->city_town_village;
    }

    /**
     * Generated from protobuf field <code>string city_town_village = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCityTownVillage($var)
    {
        GPBUtil::checkString($var, True);
        $this->city_town_village = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pincode = 4;</code>
     * @return string
     */
    public function getPincode()
    {
        return $this->pincode;
    }

    /**
     * Generated from protobuf field <code>string pincode = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPincode($var)
    {
        GPBUtil::checkString($var, True);
        $this->pincode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 district_id = 5;</code>
     * @return int
     */
    public function getDistrictId()
    {
        return $this->district_id;
    }

    /**
     * Generated from protobuf field <code>int32 district_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDistrictId($var)
    {
        GPBUtil::checkInt32($var);
        $this->district_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 state_id = 6;</code>
     * @return int
     */
    public function getStateId()
    {
        return $this->state_id;
    }

    /**
     * Generated from protobuf field <code>int32 state_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStateId($var)
    {
        GPBUtil::checkInt32($var);
        $this->state_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double latitude = 7;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>double latitude = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double longitude = 8;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>double longitude = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->longitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 created_by = 9;</code>
     * @return int
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Generated from protobuf field <code>int32 created_by = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 updated_by = 10;</code>
     * @return int
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Generated from protobuf field <code>int32 updated_by = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdatedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_by = $var;

        return $this;
    }

}

