<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/party.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.consumers.PartyListResponse</code>
 */
class PartyListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.consumers.PartyMessage parties = 1;</code>
     */
    private $parties;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\Consumers\PartyMessage>|\Google\Protobuf\Internal\RepeatedField $parties
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Party::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.consumers.PartyMessage parties = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParties()
    {
        return $this->parties;
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.consumers.PartyMessage parties = 1;</code>
     * @param array<\Proto\Consumers\PartyMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParties($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Consumers\PartyMessage::class);
        $this->parties = $arr;

        return $this;
    }

}

