<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/party.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.consumers.PartyResponse</code>
 */
class PartyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.consumers.PartyMessage party = 1;</code>
     */
    protected $party = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Consumers\PartyMessage $party
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Party::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.consumers.PartyMessage party = 1;</code>
     * @return \Proto\Consumers\PartyMessage|null
     */
    public function getParty()
    {
        return $this->party;
    }

    public function hasParty()
    {
        return isset($this->party);
    }

    public function clearParty()
    {
        unset($this->party);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.consumers.PartyMessage party = 1;</code>
     * @param \Proto\Consumers\PartyMessage $var
     * @return $this
     */
    public function setParty($var)
    {
        GPBUtil::checkMessage($var, \Proto\Consumers\PartyMessage::class);
        $this->party = $var;

        return $this;
    }

}

