<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumers/party.proto

namespace Proto\Consumers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.consumers.PartyMessage</code>
 */
class PartyMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 version_id = 1;</code>
     */
    protected $version_id = 0;
    /**
     * Generated from protobuf field <code>int32 party_id = 2;</code>
     */
    protected $party_id = 0;
    /**
     * Generated from protobuf field <code>int32 party_code = 3;</code>
     */
    protected $party_code = 0;
    /**
     * Generated from protobuf field <code>string party_legacy_code = 4;</code>
     */
    protected $party_legacy_code = '';
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int64 party_type_id = 6;</code>
     */
    protected $party_type_id = 0;
    /**
     * THIS IS THE FIX: Changed from ParameterValueMessage to ParameterValueProto
     *
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterValueProto party_type = 7;</code>
     */
    protected $party_type = null;
    /**
     * Generated from protobuf field <code>int64 status_id = 8;</code>
     */
    protected $status_id = 0;
    /**
     * THIS IS THE FIX: Changed from ParameterValueMessage to ParameterValueProto
     *
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterValueProto status = 9;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>int64 mobile_number = 10;</code>
     */
    protected $mobile_number = 0;
    /**
     * Generated from protobuf field <code>int64 telephone_number = 11;</code>
     */
    protected $telephone_number = 0;
    /**
     * Generated from protobuf field <code>string email_address = 12;</code>
     */
    protected $email_address = '';
    /**
     * Generated from protobuf field <code>string address = 13;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>int64 fax_number = 14;</code>
     */
    protected $fax_number = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp effective_start = 15;</code>
     */
    protected $effective_start = null;
    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp effective_end = 16;</code>
     */
    protected $effective_end = null;
    /**
     * Generated from protobuf field <code>bool is_current = 17;</code>
     */
    protected $is_current = false;
    /**
     * Generated from protobuf field <code>optional int32 created_by = 18;</code>
     */
    protected $created_by = null;
    /**
     * Generated from protobuf field <code>optional int32 updated_by = 19;</code>
     */
    protected $updated_by = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 20;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp updated_at = 21;</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $version_id
     *     @type int $party_id
     *     @type int $party_code
     *     @type string $party_legacy_code
     *     @type string $name
     *     @type int|string $party_type_id
     *     @type \Proto\Parameters\ParameterValueProto $party_type
     *           THIS IS THE FIX: Changed from ParameterValueMessage to ParameterValueProto
     *     @type int|string $status_id
     *     @type \Proto\Parameters\ParameterValueProto $status
     *           THIS IS THE FIX: Changed from ParameterValueMessage to ParameterValueProto
     *     @type int|string $mobile_number
     *     @type int|string $telephone_number
     *     @type string $email_address
     *     @type string $address
     *     @type int|string $fax_number
     *     @type \Google\Protobuf\Timestamp $effective_start
     *     @type \Google\Protobuf\Timestamp $effective_end
     *     @type bool $is_current
     *     @type int $created_by
     *     @type int $updated_by
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Party::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 version_id = 1;</code>
     * @return int|string
     */
    public function getVersionId()
    {
        return $this->version_id;
    }

    /**
     * Generated from protobuf field <code>int64 version_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->version_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 party_id = 2;</code>
     * @return int
     */
    public function getPartyId()
    {
        return $this->party_id;
    }

    /**
     * Generated from protobuf field <code>int32 party_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPartyId($var)
    {
        GPBUtil::checkInt32($var);
        $this->party_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 party_code = 3;</code>
     * @return int
     */
    public function getPartyCode()
    {
        return $this->party_code;
    }

    /**
     * Generated from protobuf field <code>int32 party_code = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPartyCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->party_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string party_legacy_code = 4;</code>
     * @return string
     */
    public function getPartyLegacyCode()
    {
        return $this->party_legacy_code;
    }

    /**
     * Generated from protobuf field <code>string party_legacy_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPartyLegacyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->party_legacy_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 party_type_id = 6;</code>
     * @return int|string
     */
    public function getPartyTypeId()
    {
        return $this->party_type_id;
    }

    /**
     * Generated from protobuf field <code>int64 party_type_id = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartyTypeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->party_type_id = $var;

        return $this;
    }

    /**
     * THIS IS THE FIX: Changed from ParameterValueMessage to ParameterValueProto
     *
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterValueProto party_type = 7;</code>
     * @return \Proto\Parameters\ParameterValueProto|null
     */
    public function getPartyType()
    {
        return $this->party_type;
    }

    public function hasPartyType()
    {
        return isset($this->party_type);
    }

    public function clearPartyType()
    {
        unset($this->party_type);
    }

    /**
     * THIS IS THE FIX: Changed from ParameterValueMessage to ParameterValueProto
     *
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterValueProto party_type = 7;</code>
     * @param \Proto\Parameters\ParameterValueProto $var
     * @return $this
     */
    public function setPartyType($var)
    {
        GPBUtil::checkMessage($var, \Proto\Parameters\ParameterValueProto::class);
        $this->party_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status_id = 8;</code>
     * @return int|string
     */
    public function getStatusId()
    {
        return $this->status_id;
    }

    /**
     * Generated from protobuf field <code>int64 status_id = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatusId($var)
    {
        GPBUtil::checkInt64($var);
        $this->status_id = $var;

        return $this;
    }

    /**
     * THIS IS THE FIX: Changed from ParameterValueMessage to ParameterValueProto
     *
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterValueProto status = 9;</code>
     * @return \Proto\Parameters\ParameterValueProto|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * THIS IS THE FIX: Changed from ParameterValueMessage to ParameterValueProto
     *
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.parameters.ParameterValueProto status = 9;</code>
     * @param \Proto\Parameters\ParameterValueProto $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Proto\Parameters\ParameterValueProto::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 mobile_number = 10;</code>
     * @return int|string
     */
    public function getMobileNumber()
    {
        return $this->mobile_number;
    }

    /**
     * Generated from protobuf field <code>int64 mobile_number = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMobileNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->mobile_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 telephone_number = 11;</code>
     * @return int|string
     */
    public function getTelephoneNumber()
    {
        return $this->telephone_number;
    }

    /**
     * Generated from protobuf field <code>int64 telephone_number = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTelephoneNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->telephone_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email_address = 12;</code>
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->email_address;
    }

    /**
     * Generated from protobuf field <code>string email_address = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setEmailAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->email_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 13;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fax_number = 14;</code>
     * @return int|string
     */
    public function getFaxNumber()
    {
        return $this->fax_number;
    }

    /**
     * Generated from protobuf field <code>int64 fax_number = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFaxNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->fax_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp effective_start = 15;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEffectiveStart()
    {
        return $this->effective_start;
    }

    public function hasEffectiveStart()
    {
        return isset($this->effective_start);
    }

    public function clearEffectiveStart()
    {
        unset($this->effective_start);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp effective_start = 15;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEffectiveStart($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->effective_start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp effective_end = 16;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEffectiveEnd()
    {
        return $this->effective_end;
    }

    public function hasEffectiveEnd()
    {
        return isset($this->effective_end);
    }

    public function clearEffectiveEnd()
    {
        unset($this->effective_end);
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp effective_end = 16;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEffectiveEnd($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->effective_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_current = 17;</code>
     * @return bool
     */
    public function getIsCurrent()
    {
        return $this->is_current;
    }

    /**
     * Generated from protobuf field <code>bool is_current = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCurrent($var)
    {
        GPBUtil::checkBool($var);
        $this->is_current = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 created_by = 18;</code>
     * @return int
     */
    public function getCreatedBy()
    {
        return isset($this->created_by) ? $this->created_by : 0;
    }

    public function hasCreatedBy()
    {
        return isset($this->created_by);
    }

    public function clearCreatedBy()
    {
        unset($this->created_by);
    }

    /**
     * Generated from protobuf field <code>optional int32 created_by = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 updated_by = 19;</code>
     * @return int
     */
    public function getUpdatedBy()
    {
        return isset($this->updated_by) ? $this->updated_by : 0;
    }

    public function hasUpdatedBy()
    {
        return isset($this->updated_by);
    }

    public function clearUpdatedBy()
    {
        unset($this->updated_by);
    }

    /**
     * Generated from protobuf field <code>optional int32 updated_by = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdatedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 20;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 20;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp updated_at = 21;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp updated_at = 21;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

