<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/system-modules.proto

namespace Proto\Modules;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.modules.CreateSystemModuleRequest</code>
 */
class CreateSystemModuleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.modules.SystemModule module = 1;</code>
     */
    protected $module = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Modules\SystemModule $module
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SystemModules::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.modules.SystemModule module = 1;</code>
     * @return \Proto\Modules\SystemModule|null
     */
    public function getModule()
    {
        return $this->module;
    }

    public function hasModule()
    {
        return isset($this->module);
    }

    public function clearModule()
    {
        unset($this->module);
    }

    /**
     * Generated from protobuf field <code>.com.kseb.consumerservice.proto.modules.SystemModule module = 1;</code>
     * @param \Proto\Modules\SystemModule $var
     * @return $this
     */
    public function setModule($var)
    {
        GPBUtil::checkMessage($var, \Proto\Modules\SystemModule::class);
        $this->module = $var;

        return $this;
    }

}

