<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/system-modules.proto

namespace Proto\Modules;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.kseb.consumerservice.proto.modules.ListSystemModulesResponse</code>
 */
class ListSystemModulesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.modules.SystemModule modules = 1;</code>
     */
    private $modules;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\Modules\SystemModule>|\Google\Protobuf\Internal\RepeatedField $modules
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SystemModules::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.modules.SystemModule modules = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getModules()
    {
        return $this->modules;
    }

    /**
     * Generated from protobuf field <code>repeated .com.kseb.consumerservice.proto.modules.SystemModule modules = 1;</code>
     * @param array<\Proto\Modules\SystemModule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setModules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Modules\SystemModule::class);
        $this->modules = $arr;

        return $this;
    }

}

